version: '3'
services:
  my-golang:
    build:
      context: ./
      dockerfile: Dockerfile
    image: golang
    container_name: my-golang
    volumes:
       - ./src:/go/src/app/src`
    command: "tail -f /dev/null"
